# Cloudflare Pages configuration
name = "blockeddrainscleareddundee-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "dundee-leads"
database_id = "64de6a91-190c-4713-ae06-dd42cf2be3eb"
